---
driver_plugin: vagrant
driver_config:
    require_chef_omnibus: false

platforms:
  - name: ubuntu-14.04-chef
    driver:
      box: ubuntu-14.04-chef
      box_url: http://bit.ly/1qBrpXj
      network:
        - ['private_network', {ip: '172.28.128.3'}]
    run_list:
      - recipe[apt]
      - recipe[ntp]

provisioner:
  name: chef_solo

suites:
  - name: default
    data_bags_path: 'test/integration/default/data_bags'
    #encrypted_data_bag_secret_key_path: 'test/integration/default/encrypted_data_bag_secret'
    run_list:
      - recipe[chef-monitor::default]
      - recipe[chef-monitor::rabbitmq]
      - recipe[chef-monitor::redis]
      - recipe[chef-monitor::_check_redis]
      - recipe[chef-monitor::_check_rabbitmq]
      - recipe[chef-monitor::_check_uchiwa]
      - recipe[chef-monitor::_handler_hipchat]
      - recipe[chef-monitor::server]
      - recipe[chef-monitor::webui]
    attributes:
      chef-monitor:
        rabbitmq_host: 172.28.128.3
        rabbitmq_port: 5671
        redis_host: 172.28.128.3
        redis_port: 6379
